---
language: python

matrix:
  include:
    - env:
        - ANSIBLE_VERSION=2.3.2
        - MOLECULE_SCENARIO=default
      python: '2.7'
    - env:
        - ANSIBLE_VERSION=2.4.2
        - MOLECULE_SCENARIO=ultimate
      python: '2.7'
    - env:
        - ANSIBLE_VERSION=2.4.2
        - MOLECULE_SCENARIO=centos
      python: '2.7'
    - env:
        - ANSIBLE_VERSION=2.4.2
        - MOLECULE_SCENARIO=minimal
      python: '2.7'
    - env:
        - ANSIBLE_VERSION=2.5.0.0
        - MOLECULE_SCENARIO=python3
      python: '3.6'

# Require the standard build environment
sudo: required

# Require Ubuntu 14.04
dist: trusty

# Require Docker
services:
  - docker

# Cache Ansible and Molecule to speed things up
cache:
  - pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -o Dpkg::Options::='--force-confold' --force-yes -y docker-ce

install:
  # Install Ansible
  - pip install "ansible~=$ANSIBLE_VERSION"

  # Install Python API for Docker (required by Molecule Docker driver)
  # Limit version as workaround for: https://github.com/ansible/ansible/issues/35612
  - pip install 'docker<3.0'

  # Install Molecule
  - pip install 'molecule==2.13.1'

  # Check Ansible version
  - ansible --version

  # Check Ansible Python version
  - ansible --version | grep "python version"

  # Check Molecule version
  - molecule --version

  # Build the Docker images
  - molecule create --scenario-name=$MOLECULE_SCENARIO
  - molecule destroy --scenario-name=$MOLECULE_SCENARIO

script:
  - molecule test --scenario-name=$MOLECULE_SCENARIO

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
