---
language: python

env:
  global:
    - MOLECULEW_USE_SYSTEM=true

jobs:
  include:
    - env:
        - MOLECULEW_ANSIBLE=2.7.15
        - MOLECULE_SCENARIO=default
      python: '2.7'
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=ultimate
      python: '2.7'
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=centos
      python: '2.7'
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=opensuse
      python: '2.7'
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=minimal
      python: '2.7'
    - env:
        - MOLECULEW_ANSIBLE=2.9.1
        - MOLECULE_SCENARIO=python3
      python: '3.6'

# Require Ubuntu 16.04
dist: xenial

# Require Docker
services:
  - docker

install:
  # Install dependencies
  - ./moleculew wrapper-install

  # Display versions
  - ./moleculew wrapper-versions

script:
  - ./moleculew test --scenario-name=$MOLECULE_SCENARIO

cache:
  directories:
    - $HOME/.moleculew

branches:
  only:
    - master
    - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
