---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2
        - test_usr3

    - name: install dependencies
      become: yes
      package:
        name:
          - tar
          - gzip
          - which
        state: present

    - name: install jdk 11
      become: yes
      package:
        name:
          - java-11-openjdk-devel
          - java-11-openjdk-jmods
          - java-11-openjdk-src
        state: present

    - name: install jdk 8
      become: yes
      package:
        name: java-1_8_0-openjdk-devel
        state: present

    - name: set facts for openjdk locations
      set_fact:
        jdk8_home: '/usr/lib64/jvm/java-1.8.0-openjdk'
        jdk11_home: '/usr/lib64/jvm/java-11-openjdk'

  roles:
    - role: ansible-role-intellij
      intellij_default_maven_home: '/test/maven/home'
      intellij_edition: community
      users:
        - username: test_usr
          intellij_group: users
          intellij_jdks:
            - name: '11'
              home: '{{ jdk11_home }}'
            - name: '1.8'
              home: '{{ jdk8_home }}'
          intellij_default_jdk: '11'
          intellij_disabled_plugins:
            - org.jetbrains.plugins.gradle
          intellij_codestyles:
            - name: GoogleStyle
              url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
          intellij_default_codestyle: GoogleStyle
          intellij_inspection_profiles:
            - name: GantSign
              url: 'https://raw.githubusercontent.com/gantsign/inspection-profile-intellij/master/GantSign.xml'
          intellij_default_inspection_profile: GantSign
          intellij_plugins:
            - google-java-format
            - Lombook Plugin
            - com.dubreuia
        - username: test_usr2
          intellij_group: users
          intellij_disabled_plugins:
          intellij_plugins: []
        - username: test_usr3
          intellij_group: users
