---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr
        - test_usr2
        - test_usr3

    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install jdk 8
      become: yes
      apt:
        name: openjdk-8-jdk-headless
        state: present

    - name: create java installation directory
      become: yes
      file:
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'
        dest: '/opt/java'

    - name: download jdk 11
      get_url:
        url: 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=hotspot&os=linux&arch=x64&release=jdk-11%2B28&type=jdk'
        dest: '/opt/java/jdk-11.tar.gz'
        force: no
        use_proxy: yes
        validate_certs: yes
        timeout: '{{ intellij_idea_download_timeout_seconds }}'
        mode: 'u=rw,go=r'

    - name: install jdk 11
      become: yes
      unarchive:
        src: '/opt/java/jdk-11.tar.gz'
        remote_src: yes
        dest: '/opt/java'
        owner: root
        group: root
        creates: '/opt/java/jdk-11+28/bin'

    - name: set facts for openjdk locations
      set_fact:
        jdk8_home: '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
        jdk11_home: '/opt/java/jdk-11+28'

  roles:
    - role: ansible-role-intellij
      intellij_default_maven_home: '/test/maven/home'
      users:
        - username: test_usr
          intellij_jdks:
            - name: '11'
              home: '{{ jdk11_home }}'
            - name: '1.8'
              home: '{{ jdk8_home }}'
          intellij_default_jdk: '1.8'
          intellij_disabled_plugins:
            - org.jetbrains.plugins.gradle
          intellij_codestyles:
            - name: GoogleStyle
              url: 'https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml'
          intellij_default_codestyle: GoogleStyle
          intellij_inspection_profiles:
            - name: GantSign
              url: 'https://raw.githubusercontent.com/gantsign/inspection-profile-intellij/master/GantSign.xml'
          intellij_default_inspection_profile: GantSign
          intellij_plugins:
            - google-java-format
            - Lombook Plugin
            - com.dubreuia
        - username: test_usr2
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
          intellij_default_jdk: '1.8'
          intellij_disabled_plugins:
          intellij_plugins: []
        - username: test_usr3
          intellij_jdks:
            - name: '1.8'
              home: '{{ jdk8_home }}'
          intellij_default_jdk: '1.8'
